### ISSUE TITLE
The "XamarinBuildAndroidAarProguardConfigs" task failed unexpectedly.

### ISSUE THREAD

**Issue by ellix4u** [jamesmontemagno/MyShoppe#24]
I get the error message bellow.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "XamarinBuildAndroidAarProguardConfigs" task failed unexpectedly.
System.IO.InvalidDataException: Central Directory corrupt. ---> System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   --- End of inner exception stack trace ---
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at Xamarin.Build.Download.XamarinBuildAndroidAarProguardConfigs.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	MyShop.Android			
![error](https://user-images.githubusercontent.com/8226793/38296574-a60c9444-37e9-11e8-8be7-83adc014716d.png)

**Comment by jamesmontemagno** [comment]
Can you let me know what version of Visual Studio you have? Help -> About

**Comment by ellix4u** [comment]
I use visual studio 2017

![image](https://user-images.githubusercontent.com/8226793/38316380-870551ec-3822-11e8-9aeb-8bcdfea042d1.png)

**Comment by jamesmontemagno** [comment]
I have 15.6.4, the latest stable, which has a lot of fixes in it and it is building good for me here. I would highly recommend upgrading to the latest VS 2017 version for sure ;)


I am going to bump the Xamarin.Build.Download to 0.4.9, however some other said that 0.4.5 may work for older versions.

**Comment by ellix4u** [comment]
Well, i can't update now but the solution should be able to work with at least any vs2015-2017. I get a lot of error(as below) after i downgraded to Xamarin.Build.Download to 0.4.5.

![image](https://user-images.githubusercontent.com/8226793/38353755-5d5c7388-38af-11e8-8904-06dd52c72662.png)

**Comment by jamesmontemagno** [comment]
I optimize all solutions for the latest version of VS 2017 which is what I have currently. I can't go backwards in VS world to test really at all. I would say try 0.4.9 and see what it says. Do a full clean and re-compile. I can't reproduce locally.

**Comment by ellix4u** [comment]
OK. But i have tried 0.4.9 (check the first message and picture).

**Comment by jamesmontemagno** [comment]
So, I have to assume it was an issue that they fixed with newer versions of VS 2017.

I am not sure why that even comes up seeing progaurd isn't even on in the project properties. I tried it on another machine and seemed to be working for me. 

Could you try one more thing just to see and install 0.4.4?

Another question is if you had upgraded any other libraries at all?

**Comment by flyzzy** [comment]
i have same problem

**Comment by flyzzy** [comment]
1>------ Rebuild All started: Project: SettingsConnecter, Configuration: Debug Any CPU ------
1>SettingsConnecter -> C:\WowonderPhone\SettingsConnecter\bin\Debug\netstandard2.0\SettingsConnecter.dll
2>------ Rebuild All started: Project: FlyZzy, Configuration: Debug Any CPU ------
2>C:\WowonderPhone\WoWonder\Properties\AndroidManifest.xml : warning XA0101: @(Content) build action is not supported
2>C:\WowonderPhone\WoWonder\Scripts\jquery-2.1.1.intellisense.js : warning XA0101: @(Content) build action is not supported
2>C:\WowonderPhone\WoWonder\Scripts\jquery-2.1.1.js : warning XA0101: @(Content) build action is not supported
2>C:\WowonderPhone\WoWonder\Scripts\jquery-2.1.1.min.js : warning XA0101: @(Content) build action is not supported
2>C:\WowonderPhone\WoWonder\Scripts\nugetexample.js : warning XA0101: @(Content) build action is not supported
2>C:\WowonderPhone\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018: The "XamarinBuildAndroidAarProguardConfigs" task failed unexpectedly.
2>C:\WowonderPhone\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018: System.IO.InvalidDataException: Central Directory corrupt. ---> System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file.
2>C:\WowonderPhone\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018: 
2>C:\WowonderPhone\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2>C:\WowonderPhone\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
2>C:\WowonderPhone\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
2>C:\WowonderPhone\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
2>C:\WowonderPhone\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    --- End of inner exception stack trace ---
2>C:\WowonderPhone\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
2>C:\WowonderPhone\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
2>C:\WowonderPhone\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
2>C:\WowonderPhone\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at Xamarin.Build.Download.XamarinBuildAndroidAarProguardConfigs.Execute()
2>C:\WowonderPhone\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>C:\WowonderPhone\packages\Xamarin.Build.Download.0.4.11\build\Xamarin.Build.Download.targets(137,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========

**Comment by flyzzy** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "XamarinBuildAndroidAarProguardConfigs" task failed unexpectedly.
System.IO.InvalidDataException: Central Directory corrupt. ---> System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   --- End of inner exception stack trace ---
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at Xamarin.Build.Download.XamarinBuildAndroidAarProguardConfigs.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	FlyZzy

**Comment by bellaj** [comment]
i have the same issue , what's the reason behind?
